# Generated by Django 2.2.2 on 2021-09-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikuchi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='photo3',
        ),
    ]
