# Generated by Django 2.2.2 on 2021-09-29 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kazuma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kazuma',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
    ]
