# Generated by Django 2.2.2 on 2021-09-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hinata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='photo3',
        ),
    ]
