# Generated by Django 2.2.2 on 2021-09-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cleated_at',
            new_name='created_at',
        ),
    ]
